projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from . import views
#  HTTP REQUEST

app_name = 'recipes'

    # HTTP REQUEST
urlpatterns = [
    path('', views.home, name="home"),
    path('recipes/category/<int:category_id>/', views.category, name="category"),
    path('recipes/<int:id>/', views.recipe, name="recipe")
     #home
]

recipes/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=65)  #charfild = varchar

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)  #charfild = varchar
    slug = models.SlugField()
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.title

recipes/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Recipe
from utils.factory import make_recipe
# Create your views here.

def home(request):
    recipes = Recipe.objects.all().order_by('-id')
    return render(request, 'recipes/pages/home.html', context={
        'recipes': recipes,
        'is_descripit_block': True,
    })

def category(request, category_id):
    recipes = Recipe.objects.filter(category__id=category_id).order_by('-id')
    return render(request, 'recipes/pages/home.html', context={
        'recipes': recipes,
        'is_descripit_block': True,
})

def recipe(request, id):
    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': make_recipe(),
        'is_datail_page': True,
    })

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home{% endblock title %}HOME |

{% block content %}
<main class="main-content-container">
    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% include 'recipes/partials/recipe.html'%}
        {% endfor %}
    </div>
{% endblock %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}

{% include 'recipes/partials/head.html'%}

<title>{% block title %}!!!-!!!{% endblock title %}</title>

{% block content %}
    <div class="main-content main-content-detail container">
        {% include 'recipes/partials/recipe.html'%}
    </div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://lucenasoft.github.io/" target="_blank" rel="noreferrer noopener">By Patricio Gabriel</a>
    </div>
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/brands.min.css"
    integrity="sha512-+oRH6u1nDGSm3hH8poU85YFIVTdSnS2f+texdPGrURaJh8hzmhMiZrQth6l56P4ZQmxeZzd2DqVEMqQoJ8J89A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/fontawesome.min.css"
    integrity="sha512-RvQxwf+3zJuNwl4e0sZjQeX7kUa3o82bDETpgVCH2RiwYSZVDdFJ7N/woNigN/ldyOOoKw8584jM4plQdt8bhA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/solid.min.css"
    integrity="sha512-uj2QCZdpo8PSbRGL/g5mXek6HM/APd7k/B5Hx/rkVFPNOxAQMXD+t+bG4Zv8OAdUpydZTU3UHmyjjiHv2Ww0PA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'recipes:home' %}">
                <i class="fa-solid fa-shield-halved main-logo-icon"></i>
                <span class="main-logo-text">Chamados</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    {% if recipe.cover %}
    <div class="recipe-cover">
        <a href="{%url 'recipes:recipe' recipe.id %}">
        <img src="{{recipe.cover.url}}" alt="place holder">
    </a>
    </div>
    {% endif %}
    <div class="recipe-title-container">
        <a href="{%url 'recipes:recipe' recipe.id %}">
            <h2 class="recipe-title">
                {{recipe.title}}
            </h2>
        </a>
    </div>

    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {{recipe.author.first_name}} {{recipe.author.last_name}}
        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{recipe.created_at|date:"d/m/Y"}} às {{recipe.created_at|date:"H:i"}}
        </span>
        <span class="recipe-author-item">
            <a href="{% url 'recipes:category' recipe.category.id %}">
                <i class="fas fa-layer-group"></i>
                <span>{{recipe.category.name}}</span>
            </a>
        </span>
    </div>
    {% if is_descripit_block is not True %}
    <div class="recipe-content">
        <p>{{recipe.preparation_steps}}</p>
    </div>
    {% endif %}

    <div>
        <p> &nbsp; </p>
    </div>

    {% if is_datail_page is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{%url 'recipes:recipe' recipe.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
    {% endif %}
    </footer>
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
            <form action="" class="search-form">
                <input type="search" class="search-input" name="search">
                <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
            </form>
    </div>
</div>